name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-upload:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: command_surfer-linux
            asset_name: command_surfer-x86_64-unknown-linux-gnu
          - os: windows-latest
            artifact_name: command_surfer-windows.exe
            asset_name: command_surfer-x86_64-pc-windows-msvc.exe
          - os: macos-latest
            artifact_name: command_surfer-macos
            asset_name: command_surfer-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: my-app-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Rename artifacts
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv target/release/command_surfer.exe ${{ matrix.artifact_name }}
          else
            mv target/release/command_surfer ${{ matrix.artifact_name }}
          fi

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
